services:
  frp:
    image: ghcr.io/fatedier/frps:v0.67.0
    restart: always
    command: ['-c', '/etc/frps.toml']
    ports:
      - '7000:7000'
      - '80:80'
      - '443:443'
      - '30881:30881' # Matrix RTC TCP
      - '30882:30882/udp' # Matrix RTC UDP (Muxed)
      - '31478:31478/udp' # Matrix RTC TURN
    volumes:
      - ./frps.toml:/etc/frps.toml:ro
