services:
  frp:
    image: ghcr.io/fatedier/frps:v0.67.0
    restart: always
    command: ['-c', '/etc/frps.toml']
    ports:
      - '7000:7000'
      - '80:80'
      - '443:443'
      - '7881:7881'
      - '50100-50200:50100-50200/udp'
    volumes:
      - ./frps.toml:/etc/frps.toml:ro
