image:
  repository: ghcr.io/fatedier/frpc
  tag: v0.67.0

authToken: 'TODOCHANGEME'
serverAddr: 'frp.diluz.io'
serverPort: 7000
reverseProxyIp: 'traefik.traefik.svc.cluster.local'
matrixRtcIp: 'matrix-matrix-rtc-sfu.matrix.svc.cluster.local'
