image:
  repository: ghcr.io/fatedier/frpc
  tag: v0.67.0

authToken: 'TODOCHANGEME'
serverAddr: 'frp.diluz.io'
serverPort: 7000
reverseProxyIp: 'traefik.traefik.svc.cluster.local'
matrixRtcTcpIp: 'matrix-matrix-rtc-sfu-tcp.matrix.svc.cluster.local'
matrixRtcUdpIp: 'matrix-matrix-rtc-sfu-muxed-udp.matrix.svc.cluster.local'
matrixRtcTurnIp: 'matrix-matrix-rtc-sfu-turn.matrix.svc.cluster.local'
