image:
  repository: ghcr.io/fatedier/frpc
  tag: v0.67.0

authToken: 'TODOCHANGEME'

frpcConfig: |
  serverAddr = "frp.diluz.io"
  serverPort = 7000

  auth.token = "{{ .Envs.FRP_AUTH_TOKEN }}"

  [[proxies]]
  name = "https"
  type = "https"
  localIP = ""
  localPort = 443
  customDomains = ["celery.band", "*.celery.band", "cluster.diluz.io", "*.cluster.diluz.io"]

  [[proxies]]
  name = "http"
  type = "http"
  localIP = ""
  localPort = 80
  customDomains = ["celery.band", "*.celery.band", "cluster.diluz.io", "*.cluster.diluz.io"]
