---
apiVersion: v2
description: A chart to run traefik ingress
name: traefik
version: 0.1.2
maintainers:
  - name: sebastian
    email: sebastian@diluz.io
dependencies:
  - name: traefik
    repository: https://traefik.github.io/charts
    version: 39.0.2
