apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: matrix-rtc-udp
  namespace: matrix
spec:
  entryPoints:
    - matrix-rtc-udp
  routes:
    - services:
        - name: matrix-matrix-rtc-sfu
          port: 30882
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: matrix-rtc-tcp
  namespace: matrix
spec:
  entryPoints:
    - matrix-rtc-tcp
  routes:
    - match: HostSNI(`*`)
      services:
        - name: matrix-matrix-rtc-sfu
          port: 30881