---
apiVersion: v2
description: A chart to power uptime-kuma running on kubernetes
name: uptime-kuma
version: 0.1.2
home: https://uptime.kuma.pet/
icon: https://uptime.kuma.pet/img/icon.svg
sources:
  - https://github.com/louislam/uptime-kuma
maintainers:
  - name: sebastian
    email: sebastian@diluz.io
dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 4.6.2
