apiVersion: v2
name: matrix
description: A Matrix Helm chart for Kubernetes using ESS Community
version: 0.1.12
maintainers:
  - name: sebastian
    email: sebastian@diluz.io
dependencies:
  - name: matrix-stack
    repository: oci://ghcr.io/element-hq/ess-helm
    version: 26.2.1
