apiVersion: v2
name: matrix
description: A Matrix Helm chart for Kubernetes using ESS Community
version: 0.1.5
maintainers:
  - name: sebastian
    email: sebastian@diluz.io
dependencies:
  - name: matrix-stack
    repository: oci://ghcr.io/element-hq/ess-helm
    version: 25.12.1
