apiVersion: v2
name: matrix
description: A Matrix Helm chart for Kubernetes using ESS Community
version: 0.1.13
maintainers:
  - name: sebastian
    email: sebastian@diluz.io
dependencies:
  - name: matrix-stack
    repository: oci://ghcr.io/element-hq/ess-helm
    version: 26.2.2
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 4.6.2
