apiVersion: v2
description: A Vaultwarden Helm chart for Kubernetes
name: vaultwarden
version: 0.1.3
maintainers:
  - name: sebastian
    email: sebastian@diluz.io
dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 4.6.2
